import "./globals.css";

import { Navbar, Footer } from "@/Components/Index";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <main className="max-w-screen overflow-hidden">
          {" "}
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
